name: Build and Release

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    # permissions:
    #   contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.22]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Go for ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for ${{ matrix.os }}
        run: go build -ldflags="-s -w" -trimpath -o gh-actions-trial-${{ matrix.os }} .
